# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.destroy_all
clothing_category = Category.create(name: "Clothing")
shoes_category = Category.create(name: "Shoes")
accessory_category = Category.create(name: "Accessories")
makeup_category = Category.create(name: 'Make-Up & Fragrance')
skin_category = Category.create(name: 'Skin & Body Care')
hair_category = Category.create(name: 'Hair Care & Styling')
men_groom_category = Category.create(name: "Men's Toiletries & Grooming")
sports_category = Category.create(name: 'Sports')

Gender.destroy_all
men = Gender.create(name: "men", description: "Whether you are looking for your everyday staples or hunting for that must-have piece, our stores offer the latest to dress your Clark Kent persona or the Superman in you. And collect points while you’re at it.")
women = Gender.create(name: "women", description: "Experience the thrill of shopping. Explore our broad selection of clothing, shoes, handbags, activewear and accessories here. Keep up with the fashion trend, define your style and complete your wardrobe - all while collecting points for your next splurge.
")
beauty = Gender.create(name: "beauty", description: "You might kill the san-makeup look, but taking care of your skin is a top priority. Pamper yourself with your wide collection of skincare products. And when you’re feeling up for some glam, we have all the essentials to enhance your natural beauty. Feel even better knowing that you can collect points for every dollar you spend.")

clothing_category.gender_ids = [men.id, women.id, beauty.id]
shoes_category.gender_ids = [men.id, women.id, beauty.id]
accessory_category.gender_ids = [men.id, women.id, beauty.id]
sports_category.gender_ids = [men.id, women.id, beauty.id]
makeup_category.gender_ids = [men.id, women.id, beauty.id]
skin_category.gender_ids = [men.id, women.id, beauty.id]
hair_category.gender_ids = [men.id, women.id, beauty.id]
men_groom_category.gender_ids = [men.id, women.id, beauty.id]

Subcategory.destroy_all
men.categories.find_by_name("Clothing").subcategories.create(name: "Coats & Jackets")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Suits")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Blazers")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Waistcoats")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Sweatshirts & Hoodies")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Jumpers & Cardigans")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Shirts")  
men.categories.find_by_name("Clothing").subcategories.create(name: "T-Shirts")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Polo Shirts & Rugby Shirts")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Jeans")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Trousers")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Shorts")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Sports Clothes")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Swimwear")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Sports Swimwear")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Pyjamas & Nightwear")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Robes & Dressing")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Gowns")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Underwear")  
men.categories.find_by_name("Clothing").subcategories.create(name: "Socks")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Boots")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Trainers & Plimsolls")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Sports Footwear")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Walking & Hiking Shoes")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Slippers")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Sandals")  
men.categories.find_by_name("Shoes").subcategories.create(name: "Flip Flops")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Watches")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Jewellery")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Bags")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Wallets")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Formal Accessories")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Belts")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Hats, Gloves & Scarves")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Sunglasses")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Umbrellas")  
men.categories.find_by_name("Accessories").subcategories.create(name: "Keyrings") 


women.categories.find_by_name("Clothing").subcategories.create(name: "Dresses")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Coats & Jackets")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Knitwear")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Shirts & Tops")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Lingerie & Underwear")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Trousers & Leggins")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Jeans")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Skirts")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Jumpsuits & Paysuits")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Shorts")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Nightwear")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Swimwear & Beachwear")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Tights")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Socks")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Cashmere")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Sports Clothes")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Sports Swimsuits")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Workwear")  
women.categories.find_by_name("Clothing").subcategories.create(name: "Maternity Clotes")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Court Shoes")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Boots")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Brogues")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Loafers")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Pumps")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Sandals")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Espadrilles")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Flip Flops")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Trainers & Plimsolls")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Slippers")  
women.categories.find_by_name("Shoes").subcategories.create(name: "Sports Footwear")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Handbags, Bags & Purses")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Jewellery")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Watches")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Sunglasses")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Occasion Hats & Fascinators")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Scarves")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Hats")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Belts")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Umbrellas")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Keyrings")  
women.categories.find_by_name("Accessories").subcategories.create(name: "Handkerchiefs")  

beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Face")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Lips")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Eyes")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Nails")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Make-Up Accessories")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Perfume")  
beauty.categories.find_by_name("Make-Up & Fragrance").subcategories.create(name: "Aftershave")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Skin Care")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Treatments, Supplements & Anti-Ageing")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Beauty Cleansing Devices")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Bath & Shower")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Body Care")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Hand & Foot Care")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Tanning & Suncare")  
beauty.categories.find_by_name("Skin & Body Care").subcategories.create(name: "Body Firming & Toning")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Shampoos & Conditioners")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Oils & Treatments")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Styling & Finishing Products")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Accessories")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Brushes")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Straighteners")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Stylers")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Dryers")  
beauty.categories.find_by_name("Hair Care & Styling").subcategories.create(name: "Hair Curlers")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Gift Sets")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Skin Care")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Bath & Body")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Shaving")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Hair Care")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Grooming Devices")  
beauty.categories.find_by_name("Men's Toiletries & Grooming").subcategories.create(name: "Men's Wash Bags")